Convert publishers and series using values from yml
metanorma/nist-pubid pull request #11
Opened 2021-12-03 08:32 UTC by mico

2021-12-03 09:13 UTC, ronaldtse commented on nist_pubid.gemspec
> +  spec.add_runtime_dependency "asciidoctor"
Why do we need asciidoctor?

2021-12-03 11:54 UTC, ronaldtse commented on nist_pubid.gemspec
> +  spec.add_development_dependency "rubocop-rails", "~> 2.12.4"
Do we really need rubocop-rails?

2021-12-03 15:43 UTC, mico commented on nist_pubid.gemspec
> +  spec.add_development_dependency "rubocop-rails", "~> 2.12.4"
Because of dependency here https://github.com/riboseinc/oss-guides/blob/master/ci/rubocop.yml#L19-L20

2021-12-03 15:47 UTC, mico commented
@ronaldtse almost done. could you give me some feedback on it? and I'll do final refactoring

2021-12-03 16:40 UTC, ronaldtse commented on nist_pubid.gemspec
> +  spec.add_development_dependency "rubocop-rails", "~> 2.12.4"
Can you remove these two dependencies from this gem? It is really unnecessary. Thanks.

2021-12-03 17:30 UTC, ronaldtse requested changes

2021-12-03 17:31 UTC, ronaldtse commented
We would want to have all the tests imported from the README but that could be a separate PR.

2021-12-04 06:46 UTC, mico commented on nist_pubid.gemspec
> +  spec.add_development_dependency "rubocop-rails", "~> 2.12.4"
Are you sure? How to deal with that?
```
% bundle exec rubocop
cannot load such file -- rubocop-rails
```

2021-12-04 09:18 UTC, mico commented
@ronaldtse I believe it's ready, except working with DOI format and "Section, Supplement, Index, Insert, Errata".

2021-12-04 12:52 UTC, ronaldtse approved these changes

2021-12-04 12:52 UTC, merged