Parse NIST FIPS identifiers with 2 digits year
metanorma/nist-pubid pull request #112
Opened 2022-01-24 08:22 UTC by mico

closes #105

2022-01-24 23:43 UTC, ronaldtse requested changes

2022-01-24 23:43 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NIST FIPS PUB 54-1eJan2015" }
There are 2 NIST FIPS 54-1 entries:
<img width="666" alt="Screenshot 2022-01-25 at 7 40 38 AM" src="https://user-images.githubusercontent.com/11865/150883482-c8da8c74-6b38-4009-82e1-062618044b52.png">

But only the first one is correct. The second one has the same content but is published by AIIM/ANSI.

"NIST FIPS 54-1-Jan15" is the real "NIST FIPS 51-1". It should just be called "NIST FIPS 54-1".
https://nvlpubs.nist.gov/nistpubs/Legacy/FIPS/fipspub54-1-Jan15.pdf
<img width="583" alt="Screenshot 2022-01-25 at 7 41 21 AM" src="https://user-images.githubusercontent.com/11865/150883563-4cd19bf1-3106-488a-bd63-6f56d5725885.png">

"NIST FIPS 54-1-Jan17" is published by AIIM/ANSI, not NIST. It should not be labeled as NIST. It should be marked as "ANSI/AIIM MS5-1991" (this is not a NIST series).

<img width="494" alt="Screenshot 2022-01-25 at 7 41 45 AM" src="https://user-images.githubusercontent.com/11865/150883600-b2d079e1-cfa4-4e63-8fad-5487f25fd25e.png">

2022-01-25 03:01 UTC, mico commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NIST FIPS PUB 54-1eJan2015" }
> "NIST FIPS 54-1-Jan17" is published by AIIM/ANSI, not NIST. It should not be labeled as NIST. It should be marked as "ANSI/AIIM MS5-1991" (this is not a NIST series).

What I should do with that? Should I add "AIIM/ANSI" publisher and work with AIIM/ANSII too?

2022-01-25 04:08 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NIST FIPS PUB 54-1eJan2015" }
I think we should skip this document because it is not published by NIST. For now. 

Let us clarify with NIST on whether non NIST documents can have a NIST pubid.

2022-01-25 07:36 UTC, ronaldtse commented
Thanks @mico !

2022-01-25 07:37 UTC, merged