Parse RPT series without document sequence numbers
metanorma/nist-pubid pull request #115
Opened 2022-01-24 15:10 UTC by mico

closes #101

2022-01-24 23:52 UTC, ronaldtse requested changes

2022-01-24 23:52 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NBS RPT div9" }
I think we need more research into these numbers. "NBS report ; div9" is actually this document:
https://www.govinfo.gov/app/details/GOVPUB-C13-43251ad869fb41acd5a49a05afe80772

Which is actually "NBS RPT 3119".
<img width="575" alt="Screenshot 2022-01-25 at 7 51 20 AM" src="https://user-images.githubusercontent.com/11865/150884542-736e6a1d-fc1d-472a-b69c-dbfc2572c028.png">

For all these strange entries we should just Google them to find the correct document. Seems that they are mostly online.

2022-01-25 03:31 UTC, mico commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NBS RPT div9" }
> <img alt="Screenshot 2022-01-25 at 7 51 20 AM" width="575" src="https://user-images.githubusercontent.com/11865/150884542-736e6a1d-fc1d-472a-b69c-dbfc2572c028.png">

@ronaldtse I cannot find this document, by following your link I see another document:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/5849/150905764-c44adae0-9f3c-4c66-bab9-652ca7f97a0e.png">

Tried to google another documents, didn't find any numbers.

2022-01-25 03:58 UTC, ronaldtse commented
@mico ah you're right. Don't know why I got sent to another document. In this case it is a report without a report number...

2022-01-25 03:58 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NBS RPT div9" }
Agree with just using div9...

2022-01-25 03:59 UTC, ronaldtse commented
@mico please help merge. Thanks!

2022-01-25 04:55 UTC, merged