Parse revision for PubIDs like NBS.LCIRC.145r11/1925
metanorma/nist-pubid pull request #132
Opened 2022-01-28 12:13 UTC by mico

related #125

2022-01-31 16:55 UTC, ronaldtse requested changes

2022-01-31 16:55 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NBS LC 145r11-1925" }
This is actually wrong -- in "r11/1925", the "11/1925" actually means 1925-November. So it should be "NBS LC 145/Upd-192511".

https://www.govinfo.gov/app/details/GOVPUB-C13-9f4bd1b0713ddbfadacc1a3190157cf3
<img width="965" alt="Screenshot 2022-02-01 at 12 51 28 AM" src="https://user-images.githubusercontent.com/11865/151836952-d5b05fb8-203c-470e-a287-9f4c32fa61ce.png">

2022-01-31 16:55 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NBS LC 118r1926sup12" }
Similar to the document below, the "/" separates the month and the year.

https://www.govinfo.gov/app/details/GOVPUB-C13-0668d9f24b33835365f90efb62300b1a
<img width="1125" alt="Screenshot 2022-02-01 at 12 53 06 AM" src="https://user-images.githubusercontent.com/11865/151837268-c01e4d59-cde9-4a8c-8eae-d6485e740e4e.png">

This document should actually be: "NBS LC 118sup/Upd-192612"

2022-02-01 11:40 UTC, mico commented
@ronaldtse Converted it to update

2022-02-01 11:52 UTC, ronaldtse commented
Thanks @mico !

2022-02-01 11:52 UTC, merged