Generate correct mr for NIST FIPS and NBS FIPS
metanorma/nist-pubid pull request #78
Opened 2022-01-11 04:13 UTC by mico

closes #47

2022-01-11 04:17 UTC, ronaldtse commented
@mico tests are currently failing.

2022-01-11 04:41 UTC, ronaldtse commented
@mico the correct MR form is `LC nnnn` instead of `LCIRC nnnn` for both NBS and NIST.

https://nvlpubs.nist.gov/nistpubs/Legacy/LC/nbslettercircular1127.pdf

<img width="889" alt="Screenshot 2022-01-11 at 12 40 55 PM" src="https://user-images.githubusercontent.com/11865/148882279-53ef634f-c365-4420-9615-9cc7064681cc.png">

https://nvlpubs.nist.gov/nistpubs/Legacy/LC/nistlettercircular1136.pdf
<img width="1076" alt="Screenshot 2022-01-11 at 12 41 10 PM" src="https://user-images.githubusercontent.com/11865/148882298-2b268f58-175b-4737-a7d0-1b3c2722e1a6.png">

2022-01-11 04:41 UTC, ronaldtse requested changes

2022-01-11 04:41 UTC, ronaldtse commented on spec/nist_pubid/nist_tech_pubs_spec.rb
> +    let(:mr) { "NBS.LCIRC.897" }
`LC` not `LCIRC`.

2022-01-11 05:33 UTC, mico commented on spec/nist_pubid/nist_tech_pubs_spec.rb
> +    let(:mr) { "NBS.LCIRC.897" }
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/5849/148886766-9bf818db-d7a1-431a-8bd8-14ca3c12c3e4.png">

2022-01-11 05:33 UTC, mico commented on spec/nist_pubid/nist_tech_pubs_spec.rb
> +    let(:mr) { "NBS.LCIRC.897" }
Should we update https://github.com/metanorma/nist-pubid/blob/main/README.adoc as well?

2022-01-11 07:00 UTC, ronaldtse commented on spec/nist_pubid/nist_tech_pubs_spec.rb
> +    let(:mr) { "NBS.LCIRC.897" }
Yes, please help do that. Thanks!

2022-01-12 16:40 UTC, ronaldtse approved these changes
Thanks @mico !

2022-01-12 16:40 UTC, merged