Fix NIST FIPS identifiers with months parsed wrongly
metanorma/nist-pubid pull request #80
Opened 2022-01-11 06:04 UTC by mico

closes #72

2022-01-11 07:26 UTC, ronaldtse requested changes

2022-01-11 07:26 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:original_pubid) { "NBS FIPS 107-Mar1985" }
Can we fully parse the dates, i.e. "Mar1985" into `year: 1985, month: 03` in the PubID object?

2022-01-11 09:00 UTC, mico commented on spec/nist_pubid/document_spec.rb
> +      let(:original_pubid) { "NBS FIPS 107-Mar1985" }
> Can we fully parse the dates, i.e. "Mar1985" into `year: 1985, month: 03` in the PubID object?

Sometimes the second number is not edition (NIST SP 800-53r5).
If it's parsable date, like "NIST TN 1297-1993" then we put it to edition, but "NIST FIPS 140-3" is it edition here?
I mean sometimes edition is not a date, how we can recognize if it's edition or sequence number or volume or something else?

2022-01-11 09:07 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:original_pubid) { "NBS FIPS 107-Mar1985" }
We definitely need a pattern for "date" i.e. `\w{3,4}\d{4}`. A simplistic approach will not work.

2022-01-12 09:47 UTC, mico commented
closes #73

2022-01-12 09:51 UTC, mico commented
@ronaldtse I'm parsing dates in editions now, but now I facing with the problem I mentioned before and don't have idea yet how to deal with that. You can see tests are failing now, because:
```
expected: "NIST SP 800-53r5"
     got: "NIST SP 800r5e53"
```

How can I know "53" in "NIST SP 800-53r5" is not an edition, but part of report sequence?
For example "NIST HB 135-2020" - here it's an edition, and "3" here "NIST FIPS 140-3" is also edition?

2022-01-13 04:39 UTC, ronaldtse commented
@mico we will have to split parsing by series.
* In "SP {800-NNN}", "800-NNN" is always the report number.
* In "HB NNN-XXXX", "NNN" is always the report number.

2022-01-14 08:05 UTC, mico commented
@ronaldtse could you check if everything looks good?
In most cases it's still not clear to me if sequence should be edition or not. Opening pdfs is not helping, can't find information if it's edition or not.

2022-01-14 09:01 UTC, ronaldtse commented
> In most cases it's still not clear to me if sequence should be edition or not. Opening pdfs is not helping, can't find information if it's edition or not.

@mico Can you clarify which ones are unclear? It's hard to answer without knowing the exact instances.

2022-01-14 09:04 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NBS IR 80e2073.3" }
This is really "NBS IR 80-2073.3". Can we not change the ones that are correct right now?

<img width="926" alt="Screenshot 2022-01-14 at 5 04 23 PM" src="https://user-images.githubusercontent.com/11865/149488624-88e78dab-3c34-4ab8-a3bf-8112fa5bce46.png">

2022-01-14 09:11 UTC, ronaldtse commented on spec/nist_pubid/document_spec.rb
> +      let(:short_pubid) { "NIST GCR 17-917e45" }
As mentioned in https://github.com/metanorma/nist-pubid/pull/57#issuecomment-1008968740, which was already fixed, the GCR reports use a 2 part or 3 part number. Please revert this.

2022-01-14 09:21 UTC, ronaldtse commented
I can see there are some challenges and misunderstandings here. Regular expressions don't seem to be expressive enough to serve this purpose. We need to parse the identifier like an **onion**. Maybe try using the Parslet gem to develop and parse a grammar. Without grammar the resulting parsing will be fragile.
https://github.com/kschiess/parslet

1. The report number schema for each series can be **different**. Therefore the meaning of "-" is different. GCR takes a 2-part or 3-part number. In "SP 800-(N+){part}", the "800-(N+){part}" is always the report number, and anything after is an edition.

2. Every series should probably be a Ruby Class (we can have a generic series for simple ones) for serialisation purposes.

2022-01-14 09:37 UTC, mico commented
> 1. The report number schema for each series can be **different**. Therefore the meaning of "-" is different. GCR takes a 2-part or 3-part number. In "SP 800-(N+){part}", the "800-(N+){part}" is always the report number, and anything after is an edition.
> 2. Every series should probably be a Ruby Class (we can have a generic series for simple ones) for serialisation purposes.

How can I get schema for each series? By looking at pdf sometimes I can't understand is it edition or not.

2022-01-14 10:34 UTC, ronaldtse commented
> How can I get schema for each series? By looking at pdf sometimes I can't understand is it edition or not.

We will have to find out the schema per series and document them.

2022-01-14 17:00 UTC, mico commented
> I can see there are some challenges and misunderstandings here. Regular expressions don't seem to be expressive enough to serve this purpose. We need to parse the identifier like an **onion**. Maybe try using the Parslet gem to develop and parse a grammar. Without grammar the resulting parsing will be fragile.
> 
> https://github.com/kschiess/parslet

How soon you want to implement parsing with parslet? It is not for this pull request, right?

2022-01-15 10:13 UTC, ronaldtse commented
We don’t need to use parslet right away but it will be challenging to wrestle regular expressions. I suggest we could first have series-specific regexes which will help. We need a per series schema.

2022-01-18 07:32 UTC, ronaldtse requested changes

2022-01-18 07:32 UTC, ronaldtse commented on regexps.yaml
> +edition:
Instead of `regexps.yaml` (keeping multiple series in 1 file), can we have different series classes (keeping edition, code regexes in every series class). For series that do not need special parsing, we can use a generic class to represent. Thanks!

2022-01-19 05:10 UTC, mico commented
last commit related to #32

2022-01-19 06:14 UTC, ronaldtse approved these changes

2022-01-19 07:23 UTC, merged